outputs <- list()

# Use p-values generated by logistic regression?
LGR_PVAL <- TRUE
if (LGR_PVAL) {
  lgr_stub <- "_lgr"
} else {
  lgr_stub <- ""
}

knitr::opts_chunk$set(dev = "ragg_png")

# Create tables ---------------------------------------------------------------------

pval_tables <- list()
for (outcome in OUTCOME_VARS) {
  # Read in p-values data
  pval_results_top500 <- read_csv(glue("output/pval_results_top500_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.csv"))

  # Select only those significant at FDR5
  pval_results_fdr5 <- pval_results_top500 %>% filter(fdr5) 
  
  # Create tables
  if (nrow(pval_results_fdr5 > 0)) {
    pval_table <- pval_results_fdr5 %>%
      mutate(exposed=x1, aor_corr=exp(ln_aor_corr), crude_or = exp(ln_or), aor=exp(ln_aor), minus_log10_pval=-log10(p.value),
             conf.low=exp(ln_aor_corr-1.96*stderr_ln_aor_corr), conf.high=exp(ln_aor_corr+1.96*stderr_ln_aor_corr)) %>% 
      arrange(desc(ln_aor_corr)) %>%
      mutate(confint = paste0(scales::number(conf.low, accuracy=0.01), "-", scales::number(conf.high, accuracy=0.01))) %>%
      mutate(across(c(aor_corr, crude_or, aor, minus_log10_pval), ~ scales::number(.x, accuracy=0.01))) %>%
      select(description, exposed, aor_corr, confint, minus_log10_pval, parent, type) %>% 
      flextable %>% set_header_labels(description="Covariate", exposed="No. exposed", aor_corr="Odds ratio",
                                      confint="Confidence interval", minus_log10_pval="-log10(p-value)", parent="Parent", type="Type")
  } else {
    pval_table <- "No variables identified at FDR5"
  }
 
  # Add to list
  pval_tables[[outcome]] <- pval_table
}

render(here::here("3.2_pval_tables.Rmd"), output_file=here::here("output", glue("2_pval_table{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.docx")))

  