outputs <- list()

# Use p-values generated by logistic regression?
if (LGR_PVAL) {
  lgr_stub <- "_lgr"
} else {
  lgr_stub <- ""
}

 # Create plots----------------------------------------------------------------------------------------------------

for (outcome in OUTCOME_VARS) {
  # Read in p-values data
  pval_results_top500 <- read_csv(glue("output/pval_results_top500_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.csv"))
  maternal_dx_pval_results_top500 <- pval_results_top500 %>% filter(type=="dx" & parent=="Mother")
  paternal_dx_pval_results_top500 <- pval_results_top500 %>% filter(type=="dx" & parent=="Father")
  maternal_rx_pval_results_top500 <- pval_results_top500 %>% filter(type=="rx" & parent=="Mother") %>% mutate(code = as.numeric(code))
  paternal_rx_pval_results_top500 <- pval_results_top500 %>% filter(type=="rx" & parent=="Father") %>% mutate(code = as.numeric(code))
  
  # Find maximums
  max_minus_log10_pvalue <- max(-log10(pval_results_top500$p.value))
  max_ln_aor_corr <- max(pval_results_top500$ln_aor_corr[pval_results_top500$x1y1 > 0], na.rm=TRUE)
  min_ln_aor_corr <- min(pval_results_top500$ln_aor_corr[pval_results_top500$x1y1 > 0], na.rm=TRUE)
  
  # Calculate p-values at FDRs
  fdr1 <- pval_results_top500$p.value %>% find_max_benjamini_hochberg(0.01)
  fdr5 <- pval_results_top500$p.value %>% find_max_benjamini_hochberg(0.05)
  fdr10 <- pval_results_top500$p.value %>% find_max_benjamini_hochberg(0.10)
  fdrs <- c(fdr1, fdr5, fdr10)
  fdrs[!(c(c(0),fdrs)[1:3] < fdrs)] <- 0 # if all the same keep only strictest threshold
  
  # Label Rx results
  maternal_rx_pval_results_top500 <- maternal_rx_pval_results_top500 %>% left_join(rx_group_look_up, by=c("code" = "THERDTL"))
  paternal_rx_pval_results_top500 <- paternal_rx_pval_results_top500 %>% left_join(rx_group_look_up, by=c("code" = "THERDTL"))
  
  # Label Dx results with ICD chapter
  maternal_dx_pval_results_top500 <- maternal_dx_pval_results_top500 %>% mutate(chapter = categorise_icd9_chapter(code)) %>% mutate(chapter=fct_drop(chapter, only="Missing"))
  paternal_dx_pval_results_top500 <- paternal_dx_pval_results_top500 %>% mutate(chapter = categorise_icd9_chapter(code)) %>% mutate(chapter=fct_drop(chapter, only="Missing"))
  
  # Create static Manhattan plots 
  outputs$maternal_rx_manhattan_top500 <- maternal_rx_pval_results_top500 %>% create_static_manhattan(THRGRDS, "Therapeutic group", fdrs, scale_y = ceil(max_minus_log10_pvalue))
  outputs$paternal_rx_manhattan_top500 <- paternal_rx_pval_results_top500 %>% create_static_manhattan(THRGRDS, "Therapeutic group", fdrs, scale_y = ceil(max_minus_log10_pvalue))
  outputs$maternal_dx_manhattan_top500 <- maternal_dx_pval_results_top500 %>% create_static_manhattan(chapter, "ICD-9 Chapter", fdrs, scale_y = ceil(max_minus_log10_pvalue))
  outputs$paternal_dx_manhattan_top500 <- paternal_dx_pval_results_top500 %>% create_static_manhattan(chapter, "ICD-9 Chapter", fdrs, scale_y = ceil(max_minus_log10_pvalue))
  
  # Create static Manhattan subway plots
  outputs$maternal_rx_subway_top500 <- maternal_rx_pval_results_top500 %>% create_static_manhattan_subway(THRGRDS, "Therapeutic group", fdrs, scale_y=15)
  outputs$paternal_rx_subway_top500 <- paternal_rx_pval_results_top500 %>% create_static_manhattan_subway(THRGRDS, "Therapeutic group", fdrs, scale_y=15)
  outputs$maternal_dx_subway_top500 <- maternal_dx_pval_results_top500 %>% create_static_manhattan_subway(chapter, "ICD-9 Chapter", fdrs, scale_y=15)
  outputs$paternal_dx_subway_top500 <- paternal_dx_pval_results_top500 %>% create_static_manhattan_subway(chapter, "ICD-9 Chapter", fdrs, scale_y=15)

  # Plot log-10 p-value against RR
  outputs$maternal_rx_pval_ln_aor_corr <- maternal_rx_pval_results_top500 %>% filter(x1y1 > 0) %>% create_pval_ratio_plot(fdrs, ln_aor_corr, "adjusted odds", "aOR", max_logratio=ceil(max_ln_aor_corr), min_logratio=floor(min_ln_aor_corr), max_log10_pval=ceil(max_minus_log10_pvalue))
  outputs$paternal_rx_pval_ln_aor_corr <- paternal_rx_pval_results_top500 %>% filter(x1y1 > 0) %>% create_pval_ratio_plot(fdrs, ln_aor_corr, "adjusted odds", "aOR", max_logratio=ceil(max_ln_aor_corr), min_logratio=floor(min_ln_aor_corr), max_log10_pval=ceil(max_minus_log10_pvalue))
  outputs$maternal_dx_pval_ln_aor_corr <- maternal_dx_pval_results_top500 %>% filter(x1y1 > 0) %>% create_pval_ratio_plot(fdrs, ln_aor_corr, "adjusted odds", "aOR", max_logratio=ceil(max_ln_aor_corr), min_logratio=floor(min_ln_aor_corr), max_log10_pval=ceil(max_minus_log10_pvalue))
  outputs$paternal_dx_pval_ln_aor_corr <- paternal_dx_pval_results_top500 %>% filter(x1y1 > 0) %>% create_pval_ratio_plot(fdrs, ln_aor_corr, "adjusted odds", "aOR", max_logratio=ceil(max_ln_aor_corr), min_logratio=floor(min_ln_aor_corr), max_log10_pval=ceil(max_minus_log10_pvalue))
  
  # Save plot
  individual_plots <- FALSE
  if (individual_plots){
    for (source in c("dx", "rx")) {
      for (origin in c("maternal", "paternal")) {
        jpeg(glue("output/{origin}_{source}_manhattan_top500_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.jpeg"), units="mm", width=183, height=150, res=300, type="cairo")
        outputs[[glue("{origin}_{source}_manhattan_top500")]] %>% print()
        dev.off()
        jpeg(glue("output/{origin}_{source}_subway_top500_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.jpeg"), units="mm", width=183, height=150, res=300, type="cairo")
        outputs[[glue("{origin}_{source}_subway_top500")]] %>% print()
        dev.off()
        jpeg(glue("output/{origin}_{source}_pval_ln_aor_corr_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.jpeg"), units="mm", width=183, height=150, res=300, type="cairo")
        outputs[[glue("{origin}_{source}_pval_ln_aor_corr")]] %>% print()
        dev.off()
      }
    }
  }

  # Combined plot
  outputs$combined_subway <- ggarrange(
    outputs$maternal_dx_subway_top500 + theme(legend.position="none", axis.text.x = element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank()),
    outputs$paternal_dx_subway_top500 + theme(axis.title.y = element_blank(), 
                                                     axis.text.x = element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank()),
    outputs$maternal_rx_subway_top500 + theme(legend.position="none"), 
    outputs$paternal_rx_subway_top500 + theme(legend.position="none", axis.title.y = element_blank()), 
    nrow=2,labels=c("A","B","C","D"))
  pdf(glue("output/combined_subway_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.pdf"),width=12, height=16)
  outputs[["combined_subway"]] %>% print()
  dev.off()
  
  # Combined plot
  outputs$combined_logratio <- ggarrange(
    outputs$maternal_dx_pval_ln_aor_corr + theme(legend.position="none", axis.text.x = element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank()),
    outputs$paternal_dx_pval_ln_aor_corr + theme(axis.title.y = element_blank(), 
                                              axis.text.x = element_blank(), axis.ticks.x=element_blank(), axis.title.x=element_blank()),
    outputs$maternal_rx_pval_ln_aor_corr + theme(legend.position="none"), 
    outputs$paternal_rx_pval_ln_aor_corr + theme(legend.position="none", axis.title.y = element_blank()), 
    nrow=2,labels=c("A","B","C","D"))
  jpeg(glue("output/combined_pval_ln_aor_corr_{outcome}{lgr_stub}{singleton_stub}{window_stub}{icd_stub}{train_stub}{diabetes_stub}{threshold_stub}{prior_malformation_stub}{chrom_stub}{paternal_stub}.jpeg"), units="mm", width=300, height=300, res=300, type="cairo")
  outputs[["combined_logratio"]] %>% print()
  dev.off()
  
}

  
